# Generated by Django 4.1.6 on 2023-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentApp', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='content',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
