# Generated by Django 4.1.6 on 2023-02-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentApp', '0003_alter_appointment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
